/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/periods': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the current, previous, and next period ids and date ranges */
		get: operations['getApiV1Periods']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/characters/profile': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve information about a character. */
		get: operations['getApiV1CharactersProfile']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/guilds/boss-kill': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve information about a guild boss kill. */
		get: operations['getApiV1GuildsBosskill']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/guilds/profile': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve information about a guild. */
		get: operations['getApiV1GuildsProfile']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/affixes': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the affixes for a specific region, including the latest run seen with this affix */
		get: operations['getApiV1MythicplusAffixes']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/leaderboard-capacity': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the leaderboard capacity for a region including lowest level and time to qualify */
		get: operations['getApiV1MythicplusLeaderboardcapacity']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/run-details': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve details for a specific Mythic+ run */
		get: operations['getApiV1MythicplusRundetails']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/runs': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve information about the top runs that match the given criteria */
		get: operations['getApiV1MythicplusRuns']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/score-tiers': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the colors used for score tiers in the given season. */
		get: operations['getApiV1MythicplusScoretiers']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/season-cutoffs': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the Mythic+ Season cutoffs for a region */
		get: operations['getApiV1MythicplusSeasoncutoffs']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mythic-plus/static-data': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve mythic plus season and dungeon static data for a specific expansion (slugs, names, etc.) */
		get: operations['getApiV1MythicplusStaticdata']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/raiding/boss-rankings': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the boss rankings for a given raid and region */
		get: operations['getApiV1RaidingBossrankings']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/raiding/hall-of-fame': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the hall of fame for a given raid */
		get: operations['getApiV1RaidingHalloffame']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/raiding/progression': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve details of raiding progression for a raid */
		get: operations['getApiV1RaidingProgression']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/raiding/raid-rankings': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve the raid rankings for a given raid and region */
		get: operations['getApiV1RaidingRaidrankings']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/raiding/static-data': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** Retrieve raid and boss static data for a specific expansion (slugs, names, etc.) */
		get: operations['getApiV1RaidingStaticdata']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		Period: {
			/**
			 * @description Period ID
			 * @example 1000
			 */
			period: number
			/** @description Period start date (ISO 8601) */
			start: string
			/** @description Period end date (ISO 8601) */
			end: string
		}
		RegionPeriod: {
			/**
			 * @description Region slug
			 * @example us
			 */
			region: string
			previous: components['schemas']['Period']
			current: components['schemas']['Period']
			next: components['schemas']['Period']
		}
		/** @description Period information for each region */
		periods: components['schemas']['RegionPeriod'][]
		ViewPeriodsResponse: {
			periods: components['schemas']['periods']
		}
		/**
		 * @example horde
		 * @enum {string}
		 */
		Faction: 'horde' | 'alliance'
		/**
		 * @example us
		 * @enum {string}
		 */
		Region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
		CharacterGear: {
			/** @description Character's equipped item level */
			item_level_equipped: number
			/** @description Character's total item level (in bags) */
			item_level_total: number
			/** @description Character's artifact traits on equipped artifact weapon */
			artifact_traits: number
		}
		RaidProgression: {
			/**
			 * @description Human readable summary of progression:
			 * @example 4/10 H
			 */
			summary: string
			/**
			 * @description Expansion ID for this raid. Expansion ID. 11 = Midnight, 10 = TheWarWithin, 9 = Dragonflight, 8 = Shadowlands, 7 = BattleForAzeroth, 6 = Legion
			 * @example 11
			 */
			expansion_id: number
			/**
			 * @description Number of bosses in instance
			 * @example 10
			 */
			total_bosses: number
			/** @description Number of normal mode bosses killed */
			normal_bosses_killed: number
			/**
			 * @description Number of heroic mode bosses killed
			 * @example 4
			 */
			heroic_bosses_killed: number
			/** @description Number of mythic mode bosses killed */
			mythic_bosses_killed: number
		}
		OverallRaidProgression: {
			'tier-mn-1'?: components['schemas']['RaidProgression']
			'manaforge-omega'?: components['schemas']['RaidProgression']
			'liberation-of-undermine'?: components['schemas']['RaidProgression']
			'nerubar-palace'?: components['schemas']['RaidProgression']
			'blackrock-depths'?: components['schemas']['RaidProgression']
			'awakened-amirdrassil-the-dreams-hope'?: components['schemas']['RaidProgression']
			'awakened-aberrus-the-shadowed-crucible'?: components['schemas']['RaidProgression']
			'awakened-vault-of-the-incarnates'?: components['schemas']['RaidProgression']
			'amirdrassil-the-dreams-hope'?: components['schemas']['RaidProgression']
			'aberrus-the-shadowed-crucible'?: components['schemas']['RaidProgression']
			'vault-of-the-incarnates'?: components['schemas']['RaidProgression']
			'fated-sepulcher-of-the-first-ones'?: components['schemas']['RaidProgression']
			'fated-sanctum-of-domination'?: components['schemas']['RaidProgression']
			'fated-castle-nathria'?: components['schemas']['RaidProgression']
			'sepulcher-of-the-first-ones'?: components['schemas']['RaidProgression']
			'sanctum-of-domination'?: components['schemas']['RaidProgression']
			'castle-nathria'?: components['schemas']['RaidProgression']
			'nyalotha-the-waking-city'?: components['schemas']['RaidProgression']
			'the-eternal-palace'?: components['schemas']['RaidProgression']
			'crucible-of-storms'?: components['schemas']['RaidProgression']
			'battle-of-dazaralor'?: components['schemas']['RaidProgression']
			uldir?: components['schemas']['RaidProgression']
			'antorus-the-burning-throne'?: components['schemas']['RaidProgression']
			'tomb-of-sargeras'?: components['schemas']['RaidProgression']
			'the-nighthold'?: components['schemas']['RaidProgression']
			'trial-of-valor'?: components['schemas']['RaidProgression']
			'the-emerald-nightmare'?: components['schemas']['RaidProgression']
		}
		MythicPlusScores: {
			all: number
			dps: number
			healer: number
			tank: number
			spec_0: number
			spec_1: number
			spec_2: number
			spec_3: number
		}
		ScoreColorSegment: {
			score: number
			color: string
		}
		MythicPlusSegments: {
			all: components['schemas']['ScoreColorSegment']
			dps: components['schemas']['ScoreColorSegment']
			healer: components['schemas']['ScoreColorSegment']
			tank: components['schemas']['ScoreColorSegment']
			spec_0: components['schemas']['ScoreColorSegment']
			spec_1: components['schemas']['ScoreColorSegment']
			spec_2: components['schemas']['ScoreColorSegment']
			spec_3: components['schemas']['ScoreColorSegment']
		}
		MythicPlusScoresBySeason: {
			season: string
			scores: components['schemas']['MythicPlusScores']
			segments: components['schemas']['MythicPlusSegments']
		}
		/** @description Character's Mythic+ scores by season */
		mythic_plus_scores_by_season: components['schemas']['MythicPlusScoresBySeason'][]
		Ranks: {
			/**
			 * @description World rank
			 * @example 799
			 */
			world: number
			/**
			 * @description Region rank
			 * @example 564
			 */
			region: number
			/**
			 * @description Realm rank
			 * @example 20
			 */
			realm: number
		}
		MythicPlusRoleRanks: {
			overall: components['schemas']['Ranks']
			tank: components['schemas']['Ranks']
			healer: components['schemas']['Ranks']
			dps: components['schemas']['Ranks']
			class: components['schemas']['Ranks']
			class_tank: components['schemas']['Ranks']
			class_healer: components['schemas']['Ranks']
			class_dps: components['schemas']['Ranks']
		}
		Affix: {
			/**
			 * @description Affix ID
			 * @example 148
			 */
			id: number
			/**
			 * @description Name of the affix
			 * @example Xal'atath's Bargain: Ascendant
			 */
			name: string
			/**
			 * @description Description of the affix
			 * @example While in combat, Xal'atath rains down orbs of cosmic energy that empower enemies or players.
			 */
			description: string
			/**
			 * @description Icon file name for the affix
			 * @example inv_nullstone_cosmicvoid
			 */
			icon: string
			/**
			 * @description cdn URL to the wow icon for this affix
			 * @example https://cdn.raiderio.net/images/wow/icons/large/inv_nullstone_cosmicvoid.jpg
			 */
			icon_url: string
			/**
			 * @description Wowhead URL for the affix
			 * @example https://wowhead.com/affix=148
			 */
			wowhead_url: string
		}
		/** @description List of affixes applied to this run */
		affixes: components['schemas']['Affix'][]
		/** @description The specialization the character played during this run */
		spec: {
			id?: number
			name?: string
			slug?: string
			role?: string
			class_id?: number
			is_melee?: boolean
			ordinal?: number
			patch?: string
		} | null
		/**
		 * @description The role the character played during this run
		 * @example tank
		 * @enum {string|null}
		 */
		role: 'tank' | 'healer' | 'dps' | null
		KeystoneRun: {
			/**
			 * @description Friendly name of Dungeon
			 * @example Mists of Tirna Scithe
			 */
			dungeon: string
			/**
			 * @description Shortened or abbreviated name of Dungeon
			 * @example MISTS
			 */
			short_name: string
			/**
			 * @description Mythic+ Level of the run
			 * @example 10
			 */
			mythic_level: number
			/**
			 * @description Unique ID of this run within the specific season
			 * @example 16196237
			 */
			keystone_run_id: number
			/**
			 * Format: date-time
			 * @description When this run was completed
			 * @example 2024-09-22T03:02:51.000Z
			 */
			completed_at: string
			/**
			 * @description How long it took to complete the dungeon, in milliseconds
			 * @example 1636548
			 */
			clear_time_ms: number
			/**
			 * @description The par time for the dungeon, in milliseconds
			 * @example 1800999
			 */
			par_time_ms: number
			/**
			 * @description How many times the keystone used for this dungeon would have been upgraded after completion
			 * @example 2
			 */
			num_keystone_upgrades: number
			/**
			 * @description The map challenge mode ID for the dungeon
			 * @example 375
			 */
			map_challenge_mode_id: number
			/**
			 * @description The zone ID for the dungeon
			 * @example 13334
			 */
			zone_id: number
			/**
			 * @description The static expansion id for this particular dungeon.
			 * @example 8
			 */
			zone_expansion_id: number
			/**
			 * @description URL to the wow icon for this dungeon
			 * @example https://cdn.raiderio.net/images/wow/icons/large/achievement_dungeon_mistsoftirnascithe.jpg
			 */
			icon_url: string
			/**
			 * @description URL to the background image for this dungeon
			 * @example https://cdn.raiderio.net/images/dungeons/expansion8/base/mists-of-tirna-scithe.jpg
			 */
			background_image_url: string
			/**
			 * @description How many points this run was worth
			 * @example 326.6
			 */
			score: number
			/**
			 * @description URL to this specific run to view roster details
			 * @example https://raider.io/mythic-plus-runs/season-tww-1/5376417-10-mists-of-tirna-scithe
			 */
			url: string
			affixes: components['schemas']['affixes']
			spec: components['schemas']['spec']
			role: components['schemas']['role']
		}
		KeystoneRunList: components['schemas']['KeystoneRun'][]
		ViewCharacterProfileResponse: {
			/**
			 * @description Name of character
			 * @example Ulsoga
			 */
			name: string
			/**
			 * @description Name of character's race
			 * @example Orc
			 */
			race: string
			/**
			 * @description Name of character's class
			 * @example Warlock
			 */
			class: string
			/**
			 * @description Name of character's active spec
			 * @example Affliction
			 */
			active_spec_name: string
			/**
			 * @description Name of the role for character's active spec
			 * @example DPS
			 */
			active_spec_role: string
			/**
			 * @description Character's gender
			 * @example female
			 */
			gender: string
			faction: components['schemas']['Faction']
			/**
			 * @description Character's achievement points
			 * @example 23905
			 */
			achievement_points: number
			/**
			 * @description URL for blizzards character's thumbnail
			 * @example https://render.worldofwarcraft.com/us/character/burning-blade/0/239444992-avatar.jpg?alt=/wow/static/images/2d/avatar/1-0.jpg
			 */
			thumbnail_url: string
			region: components['schemas']['Region']
			/**
			 * @description Realm character resides on
			 * @example Skullcrusher
			 */
			realm: string
			/**
			 * Format: date
			 * @description When this character was last crawled
			 * @example 2024-10-09T04:31:20.000Z
			 */
			last_crawled_at: string
			/**
			 * @description URL for Character's profile on Raider.IO
			 * @example https://raider.io/characters/us/skullcrusher/Ulsoga
			 */
			profile_url: string
			/**
			 * @description RaiderIO Character Banner Profile
			 * @example classbanner_paladin1
			 */
			profile_banner: string
			/**
			 * @description Animated Character Page Banner
			 * @example false
			 */
			use_animated_banner?: boolean
			gear?: components['schemas']['CharacterGear']
			raid_progression?: components['schemas']['OverallRaidProgression']
			mythic_plus_scores_by_season?: components['schemas']['mythic_plus_scores_by_season']
			mythic_plus_ranks?: components['schemas']['MythicPlusRoleRanks']
			previous_mythic_plus_ranks?: components['schemas']['MythicPlusRoleRanks']
			mythic_plus_recent_runs?: components['schemas']['KeystoneRunList']
			mythic_plus_best_runs?: components['schemas']['KeystoneRunList']
			mythic_plus_alternate_runs?: components['schemas']['KeystoneRunList']
		}
		BossKill: {
			/** @description When the boss was pulled */
			pulledAt?: string | null
			/** @description When the boss was defeated */
			defeatedAt?: string | null
			/** @description Kill duration in milliseconds */
			durationMs?: number | null
			/** @description Whether the kill was successful */
			isSuccess?: boolean
			/** @description Average equipped item level of the raid */
			itemLevelEquippedAvg?: number
			/** @description Maximum equipped item level in the raid */
			itemLevelEquippedMax?: number
			/** @description Minimum equipped item level in the raid */
			itemLevelEquippedMin?: number
		}
		class: {
			id?: number
			name?: string
			slug?: string
		}
		spec1: {
			id?: number
			name?: string
			slug?: string
			role?: string
			class_id?: number
			is_melee?: boolean
			ordinal?: number
			patch?: string
		}
		race: {
			id?: number
			name?: string
			slug?: string
			faction?: string
		}
		FullRealm: {
			id?: number
			name?: string
			slug?: string
			altName?: string | null
			altSlug?: string
			locale?: string
			isConnected?: boolean
			connectedRealmId?: number
			realmType?: string
			wowRealmId?: number
			wowConnectedRealmId?: number
		}
		RegionSummary: {
			/**
			 * @description Name of the region
			 * @example United States & Oceania
			 */
			name: string
			/**
			 * @description Short name of the region
			 * @example US
			 */
			short_name: string
			/**
			 * @description Slug for the region, suitable for putting in URLs
			 * @example us
			 */
			slug: string
		}
		spells: string[]
		/** @description Corruption stats */
		corruption: {
			added?: number
			resisted?: number
			total?: number
			cloakRank?: number
			spells?: components['schemas']['spells']
		}
		/** @description Map of slot name to equipped item */
		items: Record<string, never>
		/** @description Equipped gear details */
		ItemsContainer: {
			created_at?: string | null
			updated_at?: string | null
			source?: string
			/** @description Equipped item level */
			item_level_equipped?: number
			item_level_total?: number
			artifact_traits?: number
			corruption?: components['schemas']['corruption']
			items?: components['schemas']['items']
		}
		TalentSpell: {
			id?: number
			name?: string
			icon?: string
			school?: number
			rank?: string | null
			hasCooldown?: boolean
		}
		TalentEntry: {
			id?: number
			traitDefinitionId?: number
			traitSubTreeId?: number
			type?: number
			maxRanks?: number
			spell?: components['schemas']['TalentSpell']
		}
		entries: components['schemas']['TalentEntry'][]
		TalentNode: {
			id?: number
			treeId?: number
			subTreeId?: number
			type?: number
			entries?: components['schemas']['entries']
			important?: boolean
			posX?: number
			posY?: number
			row?: number
			col?: number
		}
		TalentLoadoutNode: {
			node?: components['schemas']['TalentNode']
			entryIndex?: number
			rank?: number
		}
		/** @description Talent node selections */
		loadout: components['schemas']['TalentLoadoutNode'][]
		/** @description Active talent loadout */
		TalentLoadout: {
			/** @description Spec ID for this loadout */
			specId?: number
			heroSubTreeId?: number | null
			loadout?: components['schemas']['loadout']
			/** @description Encoded talent loadout string */
			loadoutText?: string | null
		} | null
		Spell: {
			id?: number
			name?: string
			icon?: string
			school?: number
			rank?: string | null
			hasCooldown?: boolean
		}
		/** @description Notable active auras */
		interestingAuras: components['schemas']['Spell'][]
		RecruitmentProfile: {
			/** @description Type of recruitment activity (e.g. guild_raids) */
			activity_type?: string
			/** @description Entity type (e.g. guild) */
			entity_type?: string
			/** @description Recruitment profile ID */
			recruitment_profile_id?: number
		}
		recruitmentProfiles: components['schemas']['RecruitmentProfile'][]
		/** @description Character details */
		character: {
			/** @description Character ID */
			id?: number
			/** @description Character name */
			name?: string
			class?: components['schemas']['class']
			spec?: components['schemas']['spec1']
			race?: components['schemas']['race']
			realm?: components['schemas']['FullRealm']
			region?: components['schemas']['RegionSummary']
			faction?: string
			level?: number
			gender?: string
			thumbnail?: string | null
			/** @description Equipped item level */
			itemLevelEquipped?: number
			artifactTraits?: number
			items?: components['schemas']['ItemsContainer']
			talentLoadout?: components['schemas']['TalentLoadout']
			interestingAuras?: components['schemas']['interestingAuras']
			recruitmentProfiles?: components['schemas']['recruitmentProfiles']
		}
		BossKillRosterMember: {
			character?: components['schemas']['character']
			/** @description Whether Vantus Rune was active */
			vantus?: boolean
		}
		/** @description Roster of characters in the kill */
		roster: components['schemas']['BossKillRosterMember'][]
		ViewGuildBossKillResponse: {
			kill?: components['schemas']['BossKill']
			roster?: components['schemas']['roster']
		}
		RaidDifficultyRankings: {
			normal?: components['schemas']['Ranks']
			heroic?: components['schemas']['Ranks']
			mythic?: components['schemas']['Ranks']
		}
		RaidRankings: {
			'tier-mn-1'?: components['schemas']['RaidDifficultyRankings']
			'manaforge-omega'?: components['schemas']['RaidDifficultyRankings']
			'liberation-of-undermine'?: components['schemas']['RaidDifficultyRankings']
			'nerubar-palace'?: components['schemas']['RaidDifficultyRankings']
			'blackrock-depths'?: components['schemas']['RaidDifficultyRankings']
			'awakened-amirdrassil-the-dreams-hope'?: components['schemas']['RaidDifficultyRankings']
			'awakened-aberrus-the-shadowed-crucible'?: components['schemas']['RaidDifficultyRankings']
			'awakened-vault-of-the-incarnates'?: components['schemas']['RaidDifficultyRankings']
			'amirdrassil-the-dreams-hope'?: components['schemas']['RaidDifficultyRankings']
			'aberrus-the-shadowed-crucible'?: components['schemas']['RaidDifficultyRankings']
			'vault-of-the-incarnates'?: components['schemas']['RaidDifficultyRankings']
			'fated-sepulcher-of-the-first-ones'?: components['schemas']['RaidDifficultyRankings']
			'fated-sanctum-of-domination'?: components['schemas']['RaidDifficultyRankings']
			'fated-castle-nathria'?: components['schemas']['RaidDifficultyRankings']
			'sepulcher-of-the-first-ones'?: components['schemas']['RaidDifficultyRankings']
			'sanctum-of-domination'?: components['schemas']['RaidDifficultyRankings']
			'castle-nathria'?: components['schemas']['RaidDifficultyRankings']
			'nyalotha-the-waking-city'?: components['schemas']['RaidDifficultyRankings']
			'the-eternal-palace'?: components['schemas']['RaidDifficultyRankings']
			'crucible-of-storms'?: components['schemas']['RaidDifficultyRankings']
			'battle-of-dazaralor'?: components['schemas']['RaidDifficultyRankings']
			uldir?: components['schemas']['RaidDifficultyRankings']
			'antorus-the-burning-throne'?: components['schemas']['RaidDifficultyRankings']
			'tomb-of-sargeras'?: components['schemas']['RaidDifficultyRankings']
			'the-nighthold'?: components['schemas']['RaidDifficultyRankings']
			'trial-of-valor'?: components['schemas']['RaidDifficultyRankings']
			'the-emerald-nightmare'?: components['schemas']['RaidDifficultyRankings']
		}
		ViewGuildProfileResponse: {
			/**
			 * @description Name of guild
			 * @example Ludicrous Speed
			 */
			name: string
			faction: components['schemas']['Faction']
			region: components['schemas']['Region']
			/**
			 * @description Realm guild resides on
			 * @example Skullcrusher
			 */
			realm: string
			/**
			 * @description URL for Guild's profile on Raider.IO
			 * @example https://raider.io/guilds/us/skullcrusher/Ludicrous%20Speed
			 */
			profile_url: string
			raid_rankings?: components['schemas']['RaidRankings']
			raid_progression?: components['schemas']['OverallRaidProgression']
		}
		AffixDetail: {
			/**
			 * @description Blizzard's ID for this affix
			 * @example 7
			 */
			id: number
			/**
			 * @description Friendly name for this affix
			 * @example Bolstering
			 */
			name: string
			/**
			 * @description Description of the effects of this affix
			 * @example When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.
			 */
			description: string
			/**
			 * @description URL to open details on this affix on Wowhead
			 * @example https://wowhead.com/affix=7
			 */
			wowhead_url: string
			/**
			 * @description Blizzard's Icon for this affix
			 * @example inv_misc_volatilewater
			 */
			icon?: string
			/**
			 * @description URL to the icon for this affix
			 * @example https://cdn.raiderio.net/images/wow/icons/large/inv_misc_volatilewater.jpg
			 */
			icon_url?: string
		}
		/** @description List of details for each active affix */
		affix_details: components['schemas']['AffixDetail'][]
		ViewRegionAffixesResponse: {
			region: components['schemas']['Region']
			/**
			 * @description Human readable title for the current affixes
			 * @example Bolstering, Grievous, Tyrannical
			 */
			title: string
			/** @example https://raider.io/mythic-plus-affix-rankings/all/kr/leaderboards-strict/bolstering-grievous-tyrannical */
			leaderboard_url: string
			recent_run?: components['schemas']['KeystoneRun']
			affix_details: components['schemas']['affix_details']
		}
		/** @description Localized affix names */
		LocalizedString: {
			en?: string
			ru?: string
			ko?: string
			cn?: string
			pt?: string
			it?: string
			fr?: string
			es?: string
			de?: string
			tw?: string
		}
		/** @description Localized affix descriptions */
		LocalizedString1: {
			en?: string
			ru?: string
			ko?: string
			cn?: string
			pt?: string
			it?: string
			fr?: string
			es?: string
			de?: string
			tw?: string
		}
		LeaderboardAffix: {
			id?: number
			name?: components['schemas']['LocalizedString']
			description?: components['schemas']['LocalizedString1']
			slug?: string
			icon?: string
		}
		affixes1: components['schemas']['LeaderboardAffix'][]
		ConnectedRealm: {
			id?: number
			name?: string
			slug?: string
			altName?: string | null
			altSlug?: string
			locale?: string
			isConnected?: boolean
			connectedRealmId?: number
			realmType?: string
			wowRealmId?: number
			wowConnectedRealmId?: number
		}
		connectedRealms: components['schemas']['ConnectedRealm'][]
		group_finder_activity_ids: number[]
		LeaderboardDungeon: {
			id?: number
			name?: string
			slug?: string
			short_name?: string
			expansion_id?: number
			icon_url?: string
			keystone_timer_ms?: number
			map_challenge_mode_id?: number
			num_bosses?: number
			patch?: string
			type?: string
			wowInstanceId?: number
			group_finder_activity_ids?: components['schemas']['group_finder_activity_ids']
		}
		LeaderboardLowest: {
			rank?: number
			mythicLevel?: number
			timeInMilliseconds?: number
		} | null
		RealmDungeonCapacity: {
			dungeon?: components['schemas']['LeaderboardDungeon']
			lowest?: components['schemas']['LeaderboardLowest']
		}
		dungeons: components['schemas']['RealmDungeonCapacity'][]
		RealmCapacityEntry: {
			id?: number
			connectedRealms?: components['schemas']['connectedRealms']
			dungeons?: components['schemas']['dungeons']
		}
		realms: components['schemas']['RealmCapacityEntry'][]
		RealmListing: {
			region?: components['schemas']['RegionSummary']
			affixes?: components['schemas']['affixes1']
			realms?: components['schemas']['realms']
		}
		ViewLeaderboardCapacityResponse: {
			realmListing?: components['schemas']['RealmListing']
		}
		RunDetailDungeon: {
			id?: number
			name?: string
			short_name?: string
			slug?: string
			expansion_id?: number
			icon_url?: string
			keystone_timer_ms?: number
			num_bosses?: number
			map_challenge_mode_id?: number
			patch?: string
			type?: string
			wowInstanceId?: number
			group_finder_activity_ids?: components['schemas']['group_finder_activity_ids']
		}
		RunModifier: {
			id?: number
			name?: string
			description?: string
			icon?: string
			slug?: string
		}
		weekly_modifiers: components['schemas']['RunModifier'][]
		/** @description Logged combat details including per-boss breakdowns, if available */
		logged_details: Record<string, never> | null
		LoggedSource: {
			/** @description Log source identifier */
			source?: string
			/** @description Log ID */
			logId?: string | null
		}
		/** @description Sources of logged data */
		loggedSources: components['schemas']['LoggedSource'][]
		Video: {
			/** @description Video platform (e.g. youtube) */
			type?: string
			/** @description Platform-specific video ID */
			id?: string
		}
		/** @description Associated video recordings */
		videos: components['schemas']['Video'][]
		spec2: {
			id?: number
			name?: string
			slug?: string
			role?: string
			class_id?: number
			is_melee?: boolean
			ordinal?: number
			patch?: string
		}
		community_ids: string[]
		/** @description Active stream info */
		Stream: {
			is_featured_stream?: boolean
			activity_record_id?: number
			/** @description Stream ID */
			id?: string
			/** @description Streamer username */
			name?: string
			user_id?: string
			game_id?: string
			/** @description Stream status (e.g. live) */
			type?: string
			title?: string
			community_ids?: components['schemas']['community_ids']
			viewer_count?: number
			started_at?: string
			language?: string
			thumbnail_url?: string
		} | null
		/** @description Character talent loadout */
		TalentLoadout1: {
			/** @description Spec ID for this loadout */
			specId?: number
			heroSubTreeId?: number | null
			loadout?: components['schemas']['loadout']
			/** @description Encoded talent loadout string */
			loadoutText?: string | null
		} | null
		/** @description Character flags */
		flags: Record<string, never> | null
		character1: {
			id?: number
			persona_id?: number
			name?: string
			class?: components['schemas']['class']
			spec?: components['schemas']['spec2']
			race?: components['schemas']['race']
			realm?: components['schemas']['FullRealm']
			region?: components['schemas']['RegionSummary']
			faction?: string
			level?: number
			/** @description URL path to character profile */
			path?: string
			stream?: components['schemas']['Stream']
			recruitmentProfiles?: components['schemas']['recruitmentProfiles']
			talentLoadout?: components['schemas']['TalentLoadout1']
			flags?: components['schemas']['flags']
		}
		/** @description Guild info for this roster member */
		RosterGuild: {
			id?: number
			name?: string
			displayName?: string
			faction?: string
			realm?: components['schemas']['FullRealm']
			region?: components['schemas']['RegionSummary']
			path?: string
			logo?: string | null
			color?: string
			isDefaultLogo?: boolean
		} | null
		/** @description Equipped items */
		ItemsContainer1: {
			created_at?: string | null
			updated_at?: string | null
			source?: string
			/** @description Equipped item level */
			item_level_equipped?: number
			item_level_total?: number
			artifact_traits?: number
			corruption?: components['schemas']['corruption']
			items?: components['schemas']['items']
		} | null
		/** @description M+ ranks */
		MythicPlusRanks: {
			/** @description M+ score */
			score?: number
			/** @description World rank */
			world?: number
			/** @description Region rank */
			region?: number
			/** @description Realm rank */
			realm?: number
		} | null
		/** @description Previous character info if transferred */
		oldCharacter: Record<string, never> | null
		RunRosterMember: {
			character?: components['schemas']['character1']
			/** @description Role in the group (tank, healer, dps) */
			role?: string
			guild?: components['schemas']['RosterGuild']
			items?: components['schemas']['ItemsContainer1']
			ranks?: components['schemas']['MythicPlusRanks']
			oldCharacter?: components['schemas']['oldCharacter']
			isTransfer?: boolean
			isBanned?: boolean
		}
		/** @description Run roster */
		roster1: components['schemas']['RunRosterMember'][]
		ViewMythicPlusRunDetailsResponse: {
			/** @description Season slug */
			season?: string
			/** @description Run status */
			status?: string
			dungeon?: components['schemas']['RunDetailDungeon']
			keystone_run_id?: number
			mythic_level?: number
			clear_time_ms?: number
			keystone_time_ms?: number
			completed_at?: string
			deleted_at?: string | null
			num_chests?: number
			time_remaining_ms?: number
			score?: number
			faction?: string
			weekly_modifiers?: components['schemas']['weekly_modifiers']
			num_modifiers_active?: number
			logged_run_id?: number | null
			logged_details?: components['schemas']['logged_details']
			loggedSources?: components['schemas']['loggedSources']
			keystone_team_id?: number | null
			keystone_platoon_id?: number | null
			videos?: components['schemas']['videos']
			roster?: components['schemas']['roster1']
			/** @description Privacy mode for the run */
			runPrivacyMode?: string
			replay_limit?: number
			isPatron?: boolean
			isTournamentProfile?: boolean
			canViewPrivateDetails?: boolean
			isViewingPrivateDetails?: boolean
			canManageOwnVideos?: boolean
			canManageOthersVideos?: boolean
		}
		RunDungeonSummary: {
			id?: number
			name?: string
			short_name?: string
			slug?: string
			expansion_id?: number
			icon_url?: string
			keystone_timer_ms?: number
			map_challenge_mode_id?: number
			num_bosses?: number
			patch?: string
			type?: string
			wowInstanceId?: number
			group_finder_activity_ids?: components['schemas']['group_finder_activity_ids']
		}
		RunAffix: {
			id?: number
			name?: string
			description?: string
			icon?: string
			slug?: string
		}
		/** @description Active affixes */
		weekly_modifiers1: components['schemas']['RunAffix'][]
		/** @description Platoon info if applicable */
		platoon: Record<string, never> | null
		spec3: {
			id?: number
			name?: string
			slug?: string
			role?: string
		}
		character2: {
			id?: number
			persona_id?: number
			name?: string
			class?: components['schemas']['class']
			spec?: components['schemas']['spec3']
			race?: components['schemas']['race']
			faction?: string
			level?: number
			realm?: components['schemas']['FullRealm']
			region?: components['schemas']['RegionSummary']
			path?: string
			stream?: components['schemas']['Stream']
			recruitmentProfiles?: components['schemas']['recruitmentProfiles']
			flags?: components['schemas']['flags']
		}
		RunsRosterMember: {
			character?: components['schemas']['character2']
			role?: string
			oldCharacter?: components['schemas']['oldCharacter']
			isTransfer?: boolean
			isBanned?: boolean
		}
		/** @description Run roster */
		roster2: components['schemas']['RunsRosterMember'][]
		RankedRunDetail: {
			/** @description Season slug */
			season?: string
			/** @description Run status */
			status?: string
			dungeon?: components['schemas']['RunDungeonSummary']
			/** @description Unique run ID */
			keystone_run_id?: number
			/** @description Keystone level */
			mythic_level?: number
			/** @description Clear time in ms */
			clear_time_ms?: number
			/** @description Timer for the dungeon in ms */
			keystone_time_ms?: number
			/** @description When the run was completed */
			completed_at?: string
			deleted_at?: string | null
			/** @description Number of upgrades earned */
			num_chests?: number
			/** @description Time remaining in ms */
			time_remaining_ms?: number
			/** @description Faction of the group */
			faction?: string
			weekly_modifiers?: components['schemas']['weekly_modifiers1']
			num_modifiers_active?: number
			keystone_team_id?: number | null
			keystone_platoon_id?: number | null
			logged_run_id?: number | null
			platoon?: components['schemas']['platoon']
			videos?: components['schemas']['videos']
			roster?: components['schemas']['roster2']
		}
		RankedRun: {
			/** @description Rank position */
			rank?: number
			/** @description Score for the run */
			score?: number
			run?: components['schemas']['RankedRunDetail']
		}
		/** @description List of ranked runs */
		rankings: components['schemas']['RankedRun'][]
		/** @description Echo of the query parameters used */
		params: {
			season?: string
			region?: string
			dungeon?: string
			access_key?: string
			page?: number
		}
		ViewMythicPlusRunsResponse: {
			rankings?: components['schemas']['rankings']
			/** @description URL to the leaderboard on Raider.IO */
			leaderboard_url?: string
			params?: components['schemas']['params']
		}
		/**
		 * @description RGB color as float values [0-1]
		 * @example [
		 *       1,
		 *       0.5,
		 *       0
		 *     ]
		 */
		rgbFloat: number[]
		/**
		 * @description RGB color as integer values [0-255]
		 * @example [
		 *       255,
		 *       128,
		 *       0
		 *     ]
		 */
		rgbInteger: number[]
		ScoreTier: {
			/**
			 * @description Minimum score for this color tier
			 * @example 3400
			 */
			score: number
			/**
			 * @description Hex color code for this tier
			 * @example #ff8000
			 */
			rgbHex: string
			/**
			 * @description Decimal representation of the color
			 * @example 16744448
			 */
			rgbDecimal: number
			rgbFloat: components['schemas']['rgbFloat']
			rgbInteger: components['schemas']['rgbInteger']
		}
		/** @description Score tiers sorted from highest to lowest score */
		ViewScoreTiersResponse: components['schemas']['ScoreTier'][]
		/** @description Horde faction cutoff */
		CutoffFactionQuantile: {
			quantile?: number
			quantileMinValue?: number
			quantilePopulationCount?: number
			quantilePopulationFraction?: number
			totalPopulationCount?: number
		} | null
		/** @description Alliance faction cutoff */
		CutoffFactionQuantile1: {
			quantile?: number
			quantileMinValue?: number
			quantilePopulationCount?: number
			quantilePopulationFraction?: number
			totalPopulationCount?: number
		} | null
		/** @description Combined faction cutoff */
		CutoffFactionQuantile2: {
			quantile?: number
			quantileMinValue?: number
			quantilePopulationCount?: number
			quantilePopulationFraction?: number
			totalPopulationCount?: number
		} | null
		/** @description 99.9th percentile cutoff */
		CutoffQuantile: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		}
		/** @description 99th percentile cutoff */
		CutoffQuantile1: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		}
		/** @description 90th percentile cutoff */
		CutoffQuantile2: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		}
		/** @description 75th percentile cutoff */
		CutoffQuantile3: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		}
		/** @description 60th percentile cutoff */
		CutoffQuantile4: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		}
		/** @description Keystone Legend cutoff */
		CutoffQuantile5: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		} | null
		/** @description Keystone Hero cutoff */
		CutoffQuantile6: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		} | null
		/** @description Keystone Master cutoff */
		CutoffQuantile7: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		} | null
		/** @description Keystone Conqueror cutoff */
		CutoffQuantile8: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		} | null
		/** @description Keystone Explorer cutoff */
		CutoffQuantile9: {
			/** @description Score cutoff value */
			score?: number
			horde?: components['schemas']['CutoffFactionQuantile']
			/** @description Hex color for horde score */
			hordeColor?: string | null
			alliance?: components['schemas']['CutoffFactionQuantile1']
			/** @description Hex color for alliance score */
			allianceColor?: string | null
			all?: components['schemas']['CutoffFactionQuantile2']
			/** @description Hex color for combined score */
			allColor?: string | null
		} | null
		/** @description Dungeon key level brackets */
		bracketDungeonLevels: number[]
		Model1: {
			/** @description Timestamp in ms */
			x?: number
			/** @description Score value */
			y?: number
			/** @description Population count at this point */
			total?: number
		}
		/** @description Data points */
		data: components['schemas']['Model1'][]
		/** @description 99.9th percentile trend */
		GraphDataSeries: {
			/** @description Chart type (e.g. spline) */
			type?: string
			/** @description Series display name */
			name?: string
			data?: components['schemas']['data']
		}
		/** @description 99th percentile trend */
		GraphDataSeries1: {
			/** @description Chart type (e.g. spline) */
			type?: string
			/** @description Series display name */
			name?: string
			data?: components['schemas']['data']
		}
		/** @description 90th percentile trend */
		GraphDataSeries2: {
			/** @description Chart type (e.g. spline) */
			type?: string
			/** @description Series display name */
			name?: string
			data?: components['schemas']['data']
		}
		/** @description 75th percentile trend */
		GraphDataSeries3: {
			/** @description Chart type (e.g. spline) */
			type?: string
			/** @description Series display name */
			name?: string
			data?: components['schemas']['data']
		}
		/** @description 60th percentile trend */
		GraphDataSeries4: {
			/** @description Chart type (e.g. spline) */
			type?: string
			/** @description Series display name */
			name?: string
			data?: components['schemas']['data']
		}
		/** @description Historical graph data for cutoff trends */
		graphData: {
			p999?: components['schemas']['GraphDataSeries']
			p990?: components['schemas']['GraphDataSeries1']
			p900?: components['schemas']['GraphDataSeries2']
			p750?: components['schemas']['GraphDataSeries3']
			p600?: components['schemas']['GraphDataSeries4']
		}
		SeasonCutoffs: {
			/** @description When cutoffs were last updated */
			updatedAt?: string
			region?: components['schemas']['RegionSummary']
			p999?: components['schemas']['CutoffQuantile']
			p990?: components['schemas']['CutoffQuantile1']
			p900?: components['schemas']['CutoffQuantile2']
			p750?: components['schemas']['CutoffQuantile3']
			p600?: components['schemas']['CutoffQuantile4']
			keystoneLegend?: components['schemas']['CutoffQuantile5']
			keystoneHero?: components['schemas']['CutoffQuantile6']
			keystoneMaster?: components['schemas']['CutoffQuantile7']
			keystoneConqueror?: components['schemas']['CutoffQuantile8']
			keystoneExplorer?: components['schemas']['CutoffQuantile9']
			bracketDungeonLevels?: components['schemas']['bracketDungeonLevels']
			isRemappedSeason?: boolean
			graphData?: components['schemas']['graphData']
		}
		SeasonCutoffsUI: {
			season?: string
			region?: string
			access_key?: string
		}
		ViewSeasonCutoffsResponse: {
			cutoffs?: components['schemas']['SeasonCutoffs']
			ui?: components['schemas']['SeasonCutoffsUI']
		}
		/** @description Seasonal affix, if any */
		SeasonalAffix: {
			/** @description Affix ID */
			id: number
			/** @description Affix name */
			name: string
			/** @description Affix icon */
			icon: string
		} | null
		/** @description Region-specific start dates */
		starts: Record<string, never>
		/** @description Region-specific end dates */
		ends: Record<string, never>
		DungeonStaticData: {
			/** @description Dungeon ID */
			id: number
			/** @description Challenge mode map ID */
			challenge_mode_id: number
			/** @description Dungeon slug */
			slug: string
			/** @description Dungeon name */
			name: string
			/** @description Abbreviated dungeon name */
			short_name: string
			/** @description Keystone timer in seconds */
			keystone_timer_seconds: number
			/** @description URL to dungeon icon */
			icon_url: string
			/** @description URL to dungeon background image */
			background_image_url: string
		}
		dungeons1: components['schemas']['DungeonStaticData'][]
		SeasonStaticData: {
			/**
			 * @description Season slug
			 * @example season-tww-1
			 */
			slug: string
			/**
			 * @description Season name
			 * @example The War Within Season 1
			 */
			name: string
			/** @description Blizzard season ID */
			blizzard_season_id?: number | null
			/** @description Whether this is a main season */
			is_main_season: boolean
			/**
			 * @description Abbreviated season name
			 * @example TWW S1
			 */
			short_name: string
			seasonal_affix?: components['schemas']['SeasonalAffix']
			starts: components['schemas']['starts']
			ends: components['schemas']['ends']
			dungeons: components['schemas']['dungeons1']
		}
		/** @description Seasons for the requested expansion */
		seasons: components['schemas']['SeasonStaticData'][]
		dungeons2: components['schemas']['DungeonStaticData'][]
		ViewMythicPlusStaticDataResponse: {
			seasons: components['schemas']['seasons']
			dungeons: components['schemas']['dungeons2']
		}
		RaidingGuild: {
			/** @description Guild ID */
			id?: number
			/** @description Guild name */
			name?: string
			faction?: string
			realm?: components['schemas']['FullRealm']
			region?: components['schemas']['RegionSummary']
			/** @description URL path to guild profile */
			path?: string
			/** @description Guild logo URL */
			logo?: string | null
			/** @description Guild brand color */
			color?: string
			isDefaultLogo?: boolean
			displayName?: string
		}
		EncounterDefeated: {
			slug?: string
			firstDefeated?: string | null
			lastDefeated?: string | null
		}
		encountersDefeated: components['schemas']['EncounterDefeated'][]
		/** @description Featured or top stream */
		Stream1: {
			is_featured_stream?: boolean
			activity_record_id?: number
			/** @description Stream ID */
			id?: string
			/** @description Streamer username */
			name?: string
			user_id?: string
			game_id?: string
			/** @description Stream status (e.g. live) */
			type?: string
			title?: string
			community_ids?: components['schemas']['community_ids']
			viewer_count?: number
			started_at?: string
			language?: string
			thumbnail_url?: string
		} | null
		/** @description Active streamers for this guild */
		Streamers: {
			/** @description Number of active streamers */
			count?: number
			stream?: components['schemas']['Stream1']
		}
		BossRankingEntry: {
			guild?: components['schemas']['RaidingGuild']
			/** @description Overall rank */
			rank?: number
			/** @description Region-specific rank */
			regionRank?: number | null
			encountersDefeated?: components['schemas']['encountersDefeated']
			doesVideoExist?: boolean
			/** @description Average item level */
			itemLevelAvg?: number | null
			recruitmentProfiles?: components['schemas']['recruitmentProfiles']
			streamers?: components['schemas']['Streamers']
		}
		/** @description Ranked guilds for this boss */
		bossRankings: components['schemas']['BossRankingEntry'][]
		ViewBossRankingsResponse: {
			bossRankings?: components['schemas']['bossRankings']
		}
		HallOfFameGuildEntry: {
			guild?: components['schemas']['RaidingGuild']
			rank?: number
			encountersDefeated?: components['schemas']['encountersDefeated']
			recruitmentProfiles?: components['schemas']['recruitmentProfiles']
			streamers?: components['schemas']['Streamers']
		}
		/** @description Top guilds in the hall of fame */
		winningGuilds: components['schemas']['HallOfFameGuildEntry'][]
		BossSummary: {
			encounterId?: number
			name?: string
			slug?: string
			ordinal?: number
			wingId?: number
			iconUrl?: string
		}
		DefeatedByGuild: {
			guild?: components['schemas']['RaidingGuild']
			rank?: number
			encountersDefeated?: components['schemas']['encountersDefeated']
		}
		/** @description Sample of guilds that defeated this boss */
		guilds: components['schemas']['DefeatedByGuild'][]
		DefeatedBy: {
			/** @description Total guilds that defeated this boss */
			totalCount?: number
			guilds?: components['schemas']['guilds']
		}
		AttemptGuild: {
			guild?: components['schemas']['RaidingGuild']
			rank?: number
			encountersDefeated?: components['schemas']['encountersDefeated']
		}
		/** @description Sample of guilds that attempted this boss */
		attempts: components['schemas']['AttemptGuild'][]
		AttemptedBy: {
			/** @description Total guilds that attempted this boss */
			totalCount?: number
			attempts?: components['schemas']['attempts']
		}
		HallOfFameBossKill: {
			/** @description Boss slug */
			boss?: string
			bossSummary?: components['schemas']['BossSummary']
			/** @description Kill video(s) if available */
			bossKillVideo?: string | null
			defeatedBy?: components['schemas']['DefeatedBy']
			attemptedBy?: components['schemas']['AttemptedBy']
		}
		/** @description Boss kill entries */
		bossKills: components['schemas']['HallOfFameBossKill'][]
		HallOfFame: {
			winningGuilds?: components['schemas']['winningGuilds']
			bossKills?: components['schemas']['bossKills']
		}
		ViewHallOfFameResponse: {
			hallOfFame?: components['schemas']['HallOfFame']
		}
		RealmSummary: {
			/**
			 * @description Name of the realm
			 * @example Skullcrusher
			 */
			name: string
			/**
			 * @description Slug for the realm, suitable for putting in URLs
			 * @example skullcrusher
			 */
			slug: string
			/**
			 * @description Whether the realm is part of a connected realm
			 * @example false
			 */
			isConnected: boolean
		}
		GuildSummary: {
			/**
			 * @description Internal Raider.IO ID number for this guild
			 * @example 955
			 */
			id: number
			/**
			 * @description Name of the guild
			 * @example Ludicrous Speed
			 */
			name: string
			faction: components['schemas']['Faction']
			realm?: components['schemas']['RealmSummary']
			region?: components['schemas']['RegionSummary']
			/** @description Display name for the guild */
			displayName?: string
		}
		GuildDefeatEntry: {
			/** @example 2017-01-24T17:31:00.000Z */
			defeatedAt: string
			guild?: components['schemas']['GuildSummary']
		}
		guilds1: components['schemas']['GuildDefeatEntry'][]
		RaidRaceProgressionEntry: {
			/**
			 * @description How many bosses out of all bosses in this instance
			 * @example 1
			 */
			progress: number
			/**
			 * @description The number of guilds that are at this point of progression
			 * @example 98
			 */
			totalGuilds: number
			guilds?: components['schemas']['guilds1']
		}
		progression: components['schemas']['RaidRaceProgressionEntry'][]
		ViewRaidProgressionResponse: {
			progression?: components['schemas']['progression']
		}
		RaidRankingEncounter: {
			id?: number
			slug?: string
			isDefeated?: boolean
			numPulls?: number
			pullStartedAt?: string
			bestPercent?: number
		}
		encountersPulled: components['schemas']['RaidRankingEncounter'][]
		GuildPrivacy: {
			raidPulls?: boolean
			raidPercents?: boolean
			raidComps?: boolean
			wereRaidPullsRestricted?: boolean
			wereRaidPercentsRestricted?: boolean
			wereRaidCompsRestricted?: boolean
			shareRaidUntil?: string | null
		}
		RaidRankingEntry: {
			guild?: components['schemas']['RaidingGuild']
			/** @description Overall rank */
			rank?: number
			/** @description Region-specific rank */
			regionRank?: number | null
			encountersPulled?: components['schemas']['encountersPulled']
			encountersDefeated?: components['schemas']['encountersDefeated']
			guildPrivacy?: components['schemas']['GuildPrivacy']
		}
		/** @description Ranked guilds */
		raidRankings: components['schemas']['RaidRankingEntry'][]
		ViewRaidRankingsResponse: {
			raidRankings?: components['schemas']['raidRankings']
		}
		RaidEncounter: {
			/** @description Boss ID */
			id: number
			/** @description Boss slug */
			slug: string
			/** @description Boss name */
			name: string
		}
		/** @description List of encounters in this raid */
		encounters: components['schemas']['RaidEncounter'][]
		RaidStaticData: {
			/**
			 * @description Raid ID
			 * @example 100
			 */
			id: number
			/**
			 * @description Raid slug
			 * @example nerubar-palace
			 */
			slug: string
			/**
			 * @description Raid name
			 * @example Nerub-ar Palace
			 */
			name: string
			/**
			 * @description Abbreviated raid name
			 * @example NP
			 */
			short_name: string
			/** @description Icon identifier for the raid */
			icon: string
			starts: components['schemas']['starts']
			ends: components['schemas']['ends']
			encounters: components['schemas']['encounters']
		}
		/** @description List of raids for the requested expansion */
		raids: components['schemas']['RaidStaticData'][]
		ViewRaidingStaticDataResponse: {
			raids: components['schemas']['raids']
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	getApiV1Periods: {
		parameters: {
			query?: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewPeriodsResponse']
				}
			}
		}
	}
	getApiV1CharactersProfile: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of region to look up character in. Can be one of: us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
				/** @description Name of realm that character is on. This can be in slug or title format, e.g. "Altar of Storms" or "altar-of-storms" */
				realm: string
				/** @description Name of the character to look up. This is not case sensitive. */
				name: string
				/**
				 * @description Comma separated list of fields to retrieve for this character.
				 *
				 *     General fields:
				 *     -  <b>gear</b>: retrieve high level item information for player
				 *     -  <b>talents</b>: retrieve talent and loadout information for player
				 *     -  <b>talents:categorized</b>: retrieve talent and loadout information for player, separated into class and spec talents
				 *     -  <b>guild</b>: retrieve basic information about guild the player is in
				 *     -  <b>covenant</b>: retrieve the covenant and renown level of the player
				 *
				 *     Raiding fields:
				 *     -  <b>raid_progression</b>: retrieve raid progression data for character. Defaults to Current Expansion. Can add one or more parameters to request specific raids. e.g.: raid_progression:9 would return all of Dragonflight, or raid_progression:nerubar-palace would return just Nerubar Palace. You can also specify :current-expansion, :previous-expansion, :current-tier, or :previous-tier. See the raiding/static-data endpoint for slugs, and expansion ids.
				 *
				 *     Mythic Plus fields:
				 *     -  <b>mythic_plus_scores_by_season</b>: retrieve scores by mythic plus season. You can specify one or more season by appending multiple ':<season-slug>' values to this field. You can also use the alias 'current' and 'previous' instead of a season name to request that relative season. For example: mythic_plus_scores_by_season:current will request the current season using mythic_plus_scores_by_season:season-tww-1:season-df-4 will return both seasons. Not specifying a season will default to the current season. Note: Results are returned in an array that matches the order of the seasons in the request.
				 *     -  <b>mythic_plus_ranks</b>: retrieve current season mythic plus rankings for player.
				 *     -  <b>mythic_plus_recent_runs</b>: retrieve ten most recent mythic plus runs for player (current season only).
				 *     -  <b>mythic_plus_best_runs</b>: retrieve ten most high scoring mythic plus runs for player (current season only). Specify the paramater :all to retrieve all of a character's best runs for the season.
				 *     -  <b>mythic_plus_alternate_runs</b>: retrieve ten most high scoring mythic plus alternate runs for player (current season only). Specify the paramater :all to retrieve all of a character's alternate runs for the season. This is available starting Shadowlands Season 1 Post.
				 *     -  <b>mythic_plus_highest_level_runs</b>: retrieve the player's ten highest Mythic+ runs by Mythic+ level (current season only)
				 *     -  <b>mythic_plus_weekly_highest_level_runs</b>: retrieve the player's ten highest Mythic+ runs by Mythic+ level for the current raid week (current season only)
				 *     -  <b>mythic_plus_previous_weekly_highest_level_runs</b>: retrieve the player's ten highest Mythic+ runs by Mythic+ level for the previous raid week (current season only)
				 *     -  <b>previous_mythic_plus_ranks</b>: retrieve mythic plus rankings for player.
				 *
				 *     Other fields:
				 *     -  <b>raid_achievement_meta</b>: retrieve raid achievement meta status for a player. This request requires that you specify parameters for the specific tiers you're looking for. For example if you add ':tier21' to the field you will get the status of Tier 21's meta. Multiple tiers can be added to a single request: ':tier21:tier20:tier19'.
				 *     -  <b>raid_achievement_curve</b>: retrieve AOTC/Cutting Edge achievement status for a given raid slug (or multiple). Multiple slugs can be specified by separating them by colons.
				 */
				fields?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewCharacterProfileResponse']
				}
			}
		}
	}
	getApiV1GuildsBosskill: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of region to look up guild in. Can be one of: us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
				/** @description Name of realm that guild is on. This can be in slug or title format, e.g. "Altar of Storms" or "altar-of-storms" */
				realm: string
				/** @description Name of the guild to look up. This is not case sensitive. */
				guild: string
				/** @description Raid slug to look up */
				raid:
					| 'tier-mn-1'
					| 'manaforge-omega'
					| 'liberation-of-undermine'
					| 'nerubar-palace'
					| 'blackrock-depths'
					| 'awakened-amirdrassil-the-dreams-hope'
					| 'awakened-aberrus-the-shadowed-crucible'
					| 'awakened-vault-of-the-incarnates'
					| 'amirdrassil-the-dreams-hope'
					| 'aberrus-the-shadowed-crucible'
					| 'vault-of-the-incarnates'
					| 'fated-sepulcher-of-the-first-ones'
					| 'fated-sanctum-of-domination'
					| 'fated-castle-nathria'
					| 'sepulcher-of-the-first-ones'
					| 'sanctum-of-domination'
					| 'castle-nathria'
					| 'nyalotha-the-waking-city'
					| 'the-eternal-palace'
					| 'crucible-of-storms'
					| 'battle-of-dazaralor'
					| 'uldir'
					| 'antorus-the-burning-throne'
					| 'tomb-of-sargeras'
					| 'the-nighthold'
					| 'trial-of-valor'
					| 'the-emerald-nightmare'
				/** @description Boss slug to look up */
				boss: string
				/** @description Raid difficulty to look up */
				difficulty: 'mythic' | 'heroic' | 'normal'
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewGuildBossKillResponse']
				}
			}
		}
	}
	getApiV1GuildsProfile: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of region to look up guild in. Can be one of: us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
				/** @description Name of realm that guild is on. This can be in slug or title format, e.g. "Altar of Storms" or "altar-of-storms" */
				realm: string
				/** @description Name of the guild to look up. This is not case sensitive. */
				name: string
				/**
				 * @description Comma separated list of fields to retrieve for this guild.
				 *
				 *     Supported values:
				 *     -  <b>raid_progression</b>: retrieve raid progression data for guild. This can optionally take parameters to control
				 *        what raids you are getting data for. These parameters can be numeric expansion IDs, specific raid slugs, or the
				 *        terms "current-expansion", "previous-expansion", "current-tier", or "previous-tier".
				 *     -  <b>raid_rankings</b>: retrieve raid rankings data for guild. This can optionally take parameters to control
				 *        what raids you are getting data for. These parameters can be numeric expansion IDs, specific raid slugs, or the
				 *        terms "current-expansion", "previous-expansion", "current-tier", or "previous-tier".
				 *     -  <b>raid_encounters:RAID_SLUG:DIFFICULTY</b>: retrieve details on which encounters were defeated from a specific raid and difficulty
				 *     -  <b>members</b>: retrieve guild members details
				 */
				fields?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewGuildProfileResponse']
				}
			}
		}
	}
	getApiV1MythicplusAffixes: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of region to look up affixes for. Can be one of: us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
				/** @description Language to return name and description of affixes in. Can be one of: en, ru, ko, cn, pt, it, fr, es, de, tw */
				locale?:
					| 'en'
					| 'ru'
					| 'ko'
					| 'cn'
					| 'pt'
					| 'it'
					| 'fr'
					| 'es'
					| 'de'
					| 'tw'
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewRegionAffixesResponse']
				}
			}
		}
	}
	getApiV1MythicplusLeaderboardcapacity: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Retrieve the capacity info for the current or previous week. Supported values: <b>current</b> and <b>previous</b>. */
				scope?: 'current' | 'previous'
				/** @description Name of region to retrieve runs for. Can be one of: world, us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
				realm?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewLeaderboardCapacityResponse']
				}
			}
		}
	}
	getApiV1MythicplusRundetails: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of the season to retrieve (season-tww-3, etc.). Defaults to current season. */
				season: string
				/** @description ID of the run that you want to get details for */
				id: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewMythicPlusRunDetailsResponse']
				}
			}
		}
	}
	getApiV1MythicplusRuns: {
		parameters: {
			query?: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of season to request data for */
				season?: string
				/** @description Name of region to retrieve runs for. Can be one of: world, us, eu, kr, tw */
				region?: 'us' | 'eu' | 'tw' | 'kr' | 'cn' | 'world'
				/** @description Name of dungeon to filter by. This can be the dungeon's full name "Eye of Azshara" or its slug "eye-of-azshara". Use special keyword "all" to get the stats across all dungeons. */
				dungeon?: string
				/** @description Name of the affixes to restrict the results to. This will support affix in slug form: "bolstering-explosive-tyrannical". Additionally, you can supply just "tyrannical" or "fortified" to get the results for any affix combo with that as the final affix. Use the special keyword "current" to return the result for the current week's affixes, or "all" to retrieve results for all affixes. */
				affixes?: string
				/** @description Page of results to return. Limited to 100 pages by default, can be increased with access key to 1000. */
				page?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewMythicPlusRunsResponse']
				}
			}
		}
	}
	getApiV1MythicplusScoretiers: {
		parameters: {
			query?: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Name of the season to retrieve (season-tww-3, etc.). Defaults to current season. */
				season?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Score tiers sorted from highest to lowest score */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewScoreTiersResponse']
				}
			}
		}
	}
	getApiV1MythicplusSeasoncutoffs: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Season to retrieve cutoffs for */
				season?: string
				/** @description Region to receive cutoffs for */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewSeasonCutoffsResponse']
				}
			}
		}
	}
	getApiV1MythicplusStaticdata: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Expansion ID. 11 = Midnight, 10 = TheWarWithin, 9 = Dragonflight, 8 = Shadowlands, 7 = BattleForAzeroth, 6 = Legion */
				expansion_id: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewMythicPlusStaticDataResponse']
				}
			}
		}
	}
	getApiV1RaidingBossrankings: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Raid to look up. This can be the raid's full name ("Manaforge Omega") or its name in slug form: "manaforge-omega" */
				raid:
					| 'tier-mn-1'
					| 'manaforge-omega'
					| 'liberation-of-undermine'
					| 'nerubar-palace'
					| 'blackrock-depths'
					| 'awakened-amirdrassil-the-dreams-hope'
					| 'awakened-aberrus-the-shadowed-crucible'
					| 'awakened-vault-of-the-incarnates'
					| 'amirdrassil-the-dreams-hope'
					| 'aberrus-the-shadowed-crucible'
					| 'vault-of-the-incarnates'
					| 'fated-sepulcher-of-the-first-ones'
					| 'fated-sanctum-of-domination'
					| 'fated-castle-nathria'
					| 'sepulcher-of-the-first-ones'
					| 'sanctum-of-domination'
					| 'castle-nathria'
					| 'nyalotha-the-waking-city'
					| 'the-eternal-palace'
					| 'crucible-of-storms'
					| 'battle-of-dazaralor'
					| 'uldir'
					| 'antorus-the-burning-throne'
					| 'tomb-of-sargeras'
					| 'the-nighthold'
					| 'trial-of-valor'
					| 'the-emerald-nightmare'
				/** @description Slug of boss to look up */
				boss: string
				/** @description One of: mythic, heroic, normal */
				difficulty: 'mythic' | 'heroic' | 'normal'
				/** @description Name of region to restrict progress to. Can be a primary region: world, us, eu, kr, tw. Or a subregion: english, french, german, italian, oceanic, russian, spanish, eu-english, eu-portuguese, eu-spanish, us-english, brazil, us-spanish, us-central, us-eastern, us-mountain, us-pacific */
				region: string
				/** @description Name of realm to restrict to. Prefix with `connected-` to retrieve rankings from the connected realm. Requires that region be a standard region: us, eu, kr, tw. */
				realm?: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewBossRankingsResponse']
				}
			}
		}
	}
	getApiV1RaidingHalloffame: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/**
				 * @description Raid to look up. This can be the raid's full name ("Manaforge Omega
				 *                     ") or its name in slug form: "manaforge-omega"
				 */
				raid:
					| 'tier-mn-1'
					| 'manaforge-omega'
					| 'liberation-of-undermine'
					| 'nerubar-palace'
					| 'blackrock-depths'
					| 'awakened-amirdrassil-the-dreams-hope'
					| 'awakened-aberrus-the-shadowed-crucible'
					| 'awakened-vault-of-the-incarnates'
					| 'amirdrassil-the-dreams-hope'
					| 'aberrus-the-shadowed-crucible'
					| 'vault-of-the-incarnates'
					| 'fated-sepulcher-of-the-first-ones'
					| 'fated-sanctum-of-domination'
					| 'fated-castle-nathria'
					| 'sepulcher-of-the-first-ones'
					| 'sanctum-of-domination'
					| 'castle-nathria'
					| 'nyalotha-the-waking-city'
					| 'the-eternal-palace'
					| 'crucible-of-storms'
					| 'battle-of-dazaralor'
					| 'uldir'
					| 'antorus-the-burning-throne'
					| 'tomb-of-sargeras'
					| 'the-nighthold'
					| 'trial-of-valor'
					| 'the-emerald-nightmare'
				difficulty: 'mythic' | 'heroic' | 'normal'
				/** @description Name of region to restrict progress to. Can be one of: world, us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewHallOfFameResponse']
				}
			}
		}
	}
	getApiV1RaidingProgression: {
		parameters: {
			query: {
				/** @description Raid to look up. This can be the raid's full name ("Manaforge Omega") or its name in slug form: "manaforge-omega" */
				raid:
					| 'tier-mn-1'
					| 'manaforge-omega'
					| 'liberation-of-undermine'
					| 'nerubar-palace'
					| 'blackrock-depths'
					| 'awakened-amirdrassil-the-dreams-hope'
					| 'awakened-aberrus-the-shadowed-crucible'
					| 'awakened-vault-of-the-incarnates'
					| 'amirdrassil-the-dreams-hope'
					| 'aberrus-the-shadowed-crucible'
					| 'vault-of-the-incarnates'
					| 'fated-sepulcher-of-the-first-ones'
					| 'fated-sanctum-of-domination'
					| 'fated-castle-nathria'
					| 'sepulcher-of-the-first-ones'
					| 'sanctum-of-domination'
					| 'castle-nathria'
					| 'nyalotha-the-waking-city'
					| 'the-eternal-palace'
					| 'crucible-of-storms'
					| 'battle-of-dazaralor'
					| 'uldir'
					| 'antorus-the-burning-throne'
					| 'tomb-of-sargeras'
					| 'the-nighthold'
					| 'trial-of-valor'
					| 'the-emerald-nightmare'
				difficulty: 'mythic' | 'heroic' | 'normal'
				/** @description Name of region to restrict progress to. Can be one of: world, us, eu, kr, tw */
				region: 'us' | 'eu' | 'tw' | 'kr' | 'cn'
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewRaidProgressionResponse']
				}
			}
		}
	}
	getApiV1RaidingRaidrankings: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Raid to look up. This can be the raid's full name ("Manaforge Omega") or its name in slug form: "manaforge-omega" */
				raid:
					| 'tier-mn-1'
					| 'manaforge-omega'
					| 'liberation-of-undermine'
					| 'nerubar-palace'
					| 'blackrock-depths'
					| 'awakened-amirdrassil-the-dreams-hope'
					| 'awakened-aberrus-the-shadowed-crucible'
					| 'awakened-vault-of-the-incarnates'
					| 'amirdrassil-the-dreams-hope'
					| 'aberrus-the-shadowed-crucible'
					| 'vault-of-the-incarnates'
					| 'fated-sepulcher-of-the-first-ones'
					| 'fated-sanctum-of-domination'
					| 'fated-castle-nathria'
					| 'sepulcher-of-the-first-ones'
					| 'sanctum-of-domination'
					| 'castle-nathria'
					| 'nyalotha-the-waking-city'
					| 'the-eternal-palace'
					| 'crucible-of-storms'
					| 'battle-of-dazaralor'
					| 'uldir'
					| 'antorus-the-burning-throne'
					| 'tomb-of-sargeras'
					| 'the-nighthold'
					| 'trial-of-valor'
					| 'the-emerald-nightmare'
				/** @description One of: mythic, heroic, normal */
				difficulty: 'mythic' | 'heroic' | 'normal'
				/** @description Name of region to restrict progress to. Can be a primary region: world, us, eu, kr, tw. Or a subregion: english, french, german, italian, oceanic, russian, spanish, eu-english, eu-portuguese, eu-spanish, us-english, brazil, us-spanish, us-central, us-eastern, us-mountain, us-pacific */
				region: string
				/** @description Name of realm to restrict to. Prefix with `connected-` to retrieve rankings from the connected realm. Requires that region be a standard region: us, eu, kr, tw. */
				realm?: string
				/** @description Guild IDs of guilds to restrict the results to. Allows filtering to up to 10 different guilds. */
				guilds?: string
				limit?: number
				page?: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewRaidRankingsResponse']
				}
			}
		}
	}
	getApiV1RaidingStaticdata: {
		parameters: {
			query: {
				/** @description The API key from your RaiderIO App: http://raider.io/settings/apps. Apps with API keys have higher rate limits. */
				access_key?: string
				/** @description Expansion ID. 11 = Midnight, 10 = TheWarWithin, 9 = Dragonflight, 8 = Shadowlands, 7 = BattleForAzeroth, 6 = Legion */
				expansion_id: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Successful */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ViewRaidingStaticDataResponse']
				}
			}
		}
	}
}
