packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Auth
  "@openauthjs/openauth": "^0.4.3"
  ioredis: "^5.4.2"

  # Dev tooling
  eslint: ^9.26.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  "@types/node": ^22.14.8

  # Misc
  zod: ^3.25.28
  "@t3-oss/env-core": ^0.13.4

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.76.1
  "@trpc/client": ^11.1.2
  "@trpc/tanstack-react-query": ^11.1.2
  "@trpc/server": ^11.1.2

onlyBuiltDependencies:
  - esbuild
