packages:
    - apps/*
    - packages/*
    - tooling/*
catalog:
    typescript: ^5.9.3
    '@types/node': ^22.14.8
    '@types/react': ^19.2.1
    '@types/react-dom': ^19.2.1
    react: ^19.2.0
    react-dom: ^19.2.0
    zod: ^4.3.6
