packages:
    - apps/*
    - packages/*
    - tooling/*
catalog:
    '@t3-oss/env-core': ^0.13.8
    typescript: ^5.9.3
    '@types/node': ^22.14.8
    '@types/react': ^19.2.1
    '@types/react-dom': ^19.2.1
    react: ^19.2.0
    react-dom: ^19.2.0
    zod: ^4.3.6
overrides:
    esbuild@<=0.24.2: '>=0.25.0'
    undici@>=7.0.0 <7.24.0: '>=7.24.0'
    h3@>=2.0.0-0 <2.0.1-rc.18: '>=2.0.1-rc.18'
    h3@2.0.1-rc.14: 2.0.1-rc.20
    h3@2.0.1-rc.16: 2.0.1-rc.20
    h3-v2@npm:h3@2.0.1-rc.16: npm:h3@2.0.1-rc.20
    srvx@<0.11.13: '>=0.11.13'
    next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
    kysely@>=0.26.0 <0.28.14: '>=0.28.14'
    picomatch@<2.3.2: '>=2.3.2'
    picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
    picomatch@4.0.3: 4.0.4
    brace-expansion@>=2.0.0 <2.0.3: '>=2.0.3'
    brace-expansion@>=5.0.0 <5.0.5: '>=5.0.5'
    brace-expansion@5.0.4: 5.0.5
    yaml@>=2.0.0 <2.8.3: '>=2.8.3'
    immutable@<3.8.3: '>=3.8.3 <4'
