/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/region/{regionId}/item/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch item stats for a given region */
        get: operations["GetRegionItem_getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/region/{regionId}/pet/{petSpeciesId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch pet stats for a given region */
        get: operations["GetRegionPet_getPet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/region/{regionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch all item stats for a given region */
        get: operations["ListRegionItems_listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ah/{auctionHouseId}/item/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch item stats for a given auction house */
        get: operations["GetAuctionHouseItem_getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ah/{auctionHouseId}/pet/{petSpeciesId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch pet stats for a given auction house */
        get: operations["GetAuctionHousePet_getPet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ah/{auctionHouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch all item stats for a given auction house */
        get: operations["ListAuctionHouseItems_listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegionItemStat: {
            regionId: number;
            itemId: Record<string, never>;
            petSpeciesId: Record<string, never>;
            marketValue: number;
            quantity: number;
            historical: number;
            avgSalePrice: number;
            saleRate: number;
            soldPerDay: number;
        };
        AuctionHouseItemStat: {
            auctionHouseId: number;
            itemId: Record<string, never>;
            petSpeciesId: Record<string, never>;
            numAuctions: number;
            marketValue: number;
            minBuyout: number;
            historical: number;
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetRegionItem_getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regionId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionItemStat"];
                };
            };
        };
    };
    GetRegionPet_getPet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regionId: number;
                petSpeciesId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionItemStat"];
                };
            };
        };
    };
    ListRegionItems_listItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetAuctionHouseItem_getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionHouseId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionHouseItemStat"];
                };
            };
        };
    };
    GetAuctionHousePet_getPet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionHouseId: number;
                petSpeciesId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionHouseItemStat"];
                };
            };
        };
    };
    ListAuctionHouseItems_listItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionHouseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
