/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auction-houses/{auctionHouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch info on a specific auction house */
        get: operations["v1-GetAuctionHouse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/realms/{realmId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch info on a specific realm */
        get: operations["v1-GetRealms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/realms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch all realms */
        get: operations["v1-GetRealm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{regionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a specific region */
        get: operations["v1-GetRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch all regions */
        get: operations["v1-GetRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{regionId}/realms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch realms within a region */
        get: operations["v1-GetRegionRealms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuctionHouseRegionResource: {
            regionId: number;
            name: string;
            gmtOffset: number;
            gameVersion: string;
        };
        AuctionHouseRealmResource: {
            realmId: number;
            name: string;
            localizedName: string;
            locale: string;
        };
        AuctionHouseResource: {
            connectedRealmId: number;
            faction: string;
            region: components["schemas"]["AuctionHouseRegionResource"];
            realms: components["schemas"]["AuctionHouseRealmResource"][];
        };
        ItemizedMetadataResponse: {
            totalItems: number;
        };
        ItemizedResponse: {
            items: string[];
            metadata: components["schemas"]["ItemizedMetadataResponse"];
        };
        AuctionHouseIndexResponse: {
            auctionHouseId: number;
            type: string;
            lastModified: number;
        };
        RealmResponse: {
            realmId: number;
            regionId: number;
            name: string;
            localizedName: string;
            locale: string;
            auctionHouses: components["schemas"]["AuctionHouseIndexResponse"][];
        };
        GlobalRealmResponse: {
            regionId: number;
            name: string;
            regionPrefix: string;
            gmtOffset: number;
            gameVersion: string;
            lastModified: number;
            realms: components["schemas"]["RealmResponse"][];
        };
        RegionResponse: {
            regionId: number;
            name: string;
            regionPrefix: string;
            gmtOffset: number;
            gameVersion: string;
            lastModified: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "v1-GetAuctionHouse": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auctionHouseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuctionHouseResource"];
                };
            };
        };
    };
    "v1-GetRealms": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                realmId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealmResponse"];
                };
            };
        };
    };
    "v1-GetRealm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemizedResponse"] & {
                        items?: components["schemas"]["GlobalRealmResponse"][];
                    };
                };
            };
        };
    };
    "v1-GetRegion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionResponse"];
                };
            };
        };
    };
    "v1-GetRegions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemizedResponse"] & {
                        items?: components["schemas"]["RegionResponse"][];
                    };
                };
            };
        };
    };
    "v1-GetRegionRealms": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                regionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemizedResponse"] & {
                        items?: components["schemas"]["RealmResponse"][];
                    };
                };
            };
        };
    };
}
