/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WishlistPersonalImport } from './routes/wishlist/personal'
import { Route as WishlistOverviewImport } from './routes/wishlist/overview'
import { Route as GuildGuildIdRouteImport } from './routes/guild.$guildId/route'
import { Route as GuildGuildIdIndexImport } from './routes/guild.$guildId/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WishlistPersonalRoute = WishlistPersonalImport.update({
  id: '/wishlist/personal',
  path: '/wishlist/personal',
  getParentRoute: () => rootRoute,
} as any)

const WishlistOverviewRoute = WishlistOverviewImport.update({
  id: '/wishlist/overview',
  path: '/wishlist/overview',
  getParentRoute: () => rootRoute,
} as any)

const GuildGuildIdRouteRoute = GuildGuildIdRouteImport.update({
  id: '/guild/$guildId',
  path: '/guild/$guildId',
  getParentRoute: () => rootRoute,
} as any)

const GuildGuildIdIndexRoute = GuildGuildIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuildGuildIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/guild/$guildId': {
      id: '/guild/$guildId'
      path: '/guild/$guildId'
      fullPath: '/guild/$guildId'
      preLoaderRoute: typeof GuildGuildIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/wishlist/overview': {
      id: '/wishlist/overview'
      path: '/wishlist/overview'
      fullPath: '/wishlist/overview'
      preLoaderRoute: typeof WishlistOverviewImport
      parentRoute: typeof rootRoute
    }
    '/wishlist/personal': {
      id: '/wishlist/personal'
      path: '/wishlist/personal'
      fullPath: '/wishlist/personal'
      preLoaderRoute: typeof WishlistPersonalImport
      parentRoute: typeof rootRoute
    }
    '/guild/$guildId/': {
      id: '/guild/$guildId/'
      path: '/'
      fullPath: '/guild/$guildId/'
      preLoaderRoute: typeof GuildGuildIdIndexImport
      parentRoute: typeof GuildGuildIdRouteImport
    }
  }
}

// Create and export the route tree

interface GuildGuildIdRouteRouteChildren {
  GuildGuildIdIndexRoute: typeof GuildGuildIdIndexRoute
}

const GuildGuildIdRouteRouteChildren: GuildGuildIdRouteRouteChildren = {
  GuildGuildIdIndexRoute: GuildGuildIdIndexRoute,
}

const GuildGuildIdRouteRouteWithChildren =
  GuildGuildIdRouteRoute._addFileChildren(GuildGuildIdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guild/$guildId': typeof GuildGuildIdRouteRouteWithChildren
  '/wishlist/overview': typeof WishlistOverviewRoute
  '/wishlist/personal': typeof WishlistPersonalRoute
  '/guild/$guildId/': typeof GuildGuildIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/wishlist/overview': typeof WishlistOverviewRoute
  '/wishlist/personal': typeof WishlistPersonalRoute
  '/guild/$guildId': typeof GuildGuildIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guild/$guildId': typeof GuildGuildIdRouteRouteWithChildren
  '/wishlist/overview': typeof WishlistOverviewRoute
  '/wishlist/personal': typeof WishlistPersonalRoute
  '/guild/$guildId/': typeof GuildGuildIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guild/$guildId'
    | '/wishlist/overview'
    | '/wishlist/personal'
    | '/guild/$guildId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/wishlist/overview'
    | '/wishlist/personal'
    | '/guild/$guildId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/guild/$guildId'
    | '/wishlist/overview'
    | '/wishlist/personal'
    | '/guild/$guildId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuildGuildIdRouteRoute: typeof GuildGuildIdRouteRouteWithChildren
  WishlistOverviewRoute: typeof WishlistOverviewRoute
  WishlistPersonalRoute: typeof WishlistPersonalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuildGuildIdRouteRoute: GuildGuildIdRouteRouteWithChildren,
  WishlistOverviewRoute: WishlistOverviewRoute,
  WishlistPersonalRoute: WishlistPersonalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/guild/$guildId",
        "/wishlist/overview",
        "/wishlist/personal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/guild/$guildId": {
      "filePath": "guild.$guildId/route.tsx",
      "children": [
        "/guild/$guildId/"
      ]
    },
    "/wishlist/overview": {
      "filePath": "wishlist/overview.tsx"
    },
    "/wishlist/personal": {
      "filePath": "wishlist/personal.tsx"
    },
    "/guild/$guildId/": {
      "filePath": "guild.$guildId/index.tsx",
      "parent": "/guild/$guildId"
    }
  }
}
ROUTE_MANIFEST_END */
